session_data:
  transaction_id: null
  message_id: null
  last_action: null
  mock_type: null
  city_code: null
  bap_id: null
  bap_uri: null
  bpp_id: null
  bpp_uri: null
  start_code: null
  end_code: null
  buyer_app_fee: null
  vehicle_type: null
  fulfillments: []
  category_ids: []
  provider_id: null
  fulfillment_ids: []
  item_ids: []
  items: []
  selected_items: []
  selected_item_ids: []
  billing: {}
  payments: []
  updated_payments: []
  order_id: null
  status: null
  error_code: null
  error_message: null
  quote: null
  ref_id: null
  ttl: null
  usecaseId: null
  on_search_items: []
  payment_type: null
  payment: {}
  is_cod: null
  cancellation: {}
  domain: null
  linked_order: {}
  confirm_fulfillments: []
  rate_basis: null
  fulfillment: {}
  on_init_items: []
  retail_category: null
  collection_amount: null
  feature_surge_fee: null
  feature_cancellation_terms: null
  cancellation_terms: []
  rto_action: null
  rto_verification_code: null
  igm_action: null
  latest_issue_payload: null
  latest_on_issue_payload: null
  on_search_batch_fulfillment: {}
  rider_count: null
  order_count: null
  update_fulfillments: []
