save-data:
  message_id: "$.context.message_id"
  status: "$.message.order.status"
  cancellation_quote: "$.message.order.quote"
  cancellation_reason: "$.message.order.cancellation"
  cancellation_fulfillments: "$.message.order.fulfillments[*]"