codes:
  - code: 100
    action_id: search
    action: search
    default: search/default.yaml
    message_id: true
  - code: 101
    action_id: on_search
    action: on_search
    default: on_search/default.yaml
    message_id: false
  - code: 102
    action_id: search_1
    action: search
    default: search/search_1/default.yaml
    message_id: true
  - code: 103
    action_id: on_search_1
    action: on_search
    default: on_search/on_search_1/default.yaml
    message_id: false
  - code: 104
    action_id: on_search_2
    action: on_search
    default: on_search/on_search_2/default.yaml
    message_id: true
  - code: 105
    action_id: select
    action: select
    default: select/default.yaml
    message_id: true
  - code: 106
    action_id: on_select
    action: on_select
    default: on_select/default.yaml
    message_id: false
  - code: 107
    action_id: init
    action: init
    default: init/default.yaml
    message_id: true
  - code: 108
    action_id: on_init
    action: on_init
    default: on_init/default.yaml
    message_id: false
  - code: 109
    action_id: confirm
    action: confirm
    default: confirm/default.yaml
    message_id: true
  - code: 110
    action_id: on_confirm
    action: on_confirm
    default: on_confirm/default.yaml
    message_id: false
