message:
  order:
    billing:
      name: Joe Adams
    fulfillments:
      - customer:
          contact:
            phone: "9876556789"
          person:
            name: Joe Adams
        id: F1
        stops:
          - location:
              gps: "13.008935, 77.644408"
            type: START
          - location:
              gps: "12.971186, 77.586812"
            type: END
        vehicle:
          category: AUTO_RICKSHAW
          variant: AUTO_RICKSHAW
    items:
      - id: I1
    payments:
      - collected_by: BPP
        status: NOT-PAID
        type: ON-FULFILLMENT
    provider:
      id: P1
    tags:
      - descriptor:
          name: BAP Terms of Engagement
          code: BAP_TERMS
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: PT1D
          - descriptor:
              code: SETTLEMENT_BASIS
            value: DELIVERY
          - descriptor:
              code: SETTLEMENT_TYPE
            value: UPI
          - descriptor:
              code: SETTLEMENT_AMOUNT
            value: "144.54"
          - descriptor:
              code: MANDATORY_ARBITRATION
            value: "true"
          - descriptor:
              code: COURT_JURISDICTION
            value: New Delhi
          - descriptor:
              code: DELAY_INTEREST
            value: "5"
          - descriptor:
              code: STATIC_TERMS
            value: https://example-test-bap.com/static-terms.txt
          - descriptor:
              code: SETTLEMENT_BANK_CODE
            value: XXXXXXXX
          - descriptor:
              code: SETTLEMENT_BANK_ACCOUNT_NUMBER
            value: xxxxxxxxxxxxxx
          - descriptor:
              code: SETTLEMENT_VIRTUAL_PAYMENT_ADDRESS
            value: 9988199772@okicic
