version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation-mock-service
    ports:
      - "3031:8000"
    env_file:
      - .env
    restart: always
