message:
  intent:
    category:
      descriptor:
        code: CULTURE_HERITAGE
    fulfillment:
      stops:
        - type: START
          location:
            gps: 28.666576, 77.233332
            circle:
              radius:
                value: '10.12'
          time:
            timestamp: '2024-06-27T04:41:16.000Z'
      vehicle:
        category: SITE
    payment:
      collected_by: BAP
    tags:
      - descriptor:
          code: BAP_TERMS
          name: BAP Terms of Engagement
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: '1'
          - descriptor:
              code: BUYER_FINDER_FEES_TYPE
            value: percent
          - descriptor:
              code: STATIC_TERMS
            value: https://api.example-bap.com/booking/terms
          - descriptor:
              code: SETTLEMENT_BASIS
            value: https://api.example-bap.com/booking/terms
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: P30D 