save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  start_location: "$.message.intent.fulfillment.stops[?(@.type=='START')].location.gps"
  intermediate_location: "$.message.intent.fulfillment.stops[?(@.type=='INTERMEDIATE_STOP')].location.gps"
  end_location: "$.message.intent.fulfillment.stops[?(@.type=='END')].location.gps"
  payment_collected_by: "$.message.intent.payment.collected_by"
  stops: "$.message.intent.fulfillment.stops[*]"
  collected_by: "$.message.intent.payment.collected_by" 
  select_payments: "$.message.order.payments"
  select_quote: "$.message.order.quote"
  on_select_cancellation_terms: "$.message.order.cancellation_terms"
  on_select_provider_tags: "$.message.order.provider.tags"
  on_select_item_tags: "$.message.order.items[*].tags"