message:
  order:
    items:
      - id: I3
        category_ids:
          - C2
        descriptor:
          name: Journey Pass
          code: Pass
        price:
          currency: INR
          value: '1500'
        quantity:
          selected:
            count: 1
        fulfillment_ids:
          - F2
        time:
          label: Validity
          duration: P30D
    provider:
      id: P1
      descriptor:
        name: ONDC Metro Rail Limited
        images:
          - url: 'https://delhimetrorail.com/logos/logo.ico'
      time:
        range:
          start: '2023-09-14T05:30:00.000Z'
          end: '2023-09-14T23:30:00.000Z'
    fulfillments:
      - id: F2
        type: TRIP
        stops:
          - type: START
            location:
              descriptor:
                name: Shaheed Sthal(New Bus Adda)
                code: SHAHEED_STHAL
              gps: '28.686576, 77.441632'
            id: '1'
          - type: END
            location:
              descriptor:
                name: Azadpur
                code: AZADPUR
              gps: '28.707358, 77.180910'
            id: '2'
            parent_stop_id: '1'
        vehicle:
          category: METRO
    quote:
      price:
        value: '1500'
        currency: INR
      breakup:
        - title: BASE_FARE
          item:
            id: I3
            price:
              currency: INR
              value: '1500'
            quantity:
              selected:
                count: 1
          price:
            currency: INR
            value: '1500'
    cancellation_terms:
      - external_ref:
          mimetype: text/html
          url: 'https://transitsolutions.com/mf/tnc.html'
    tags:
      - descriptor:
          code: SCHEDULED_INFO
        display: false
        list:
          - descriptor:
              code: GTFS
            value: 'https://metro-transit/gtfs-realtime'
