save-data:
  order_id: "$.message.order.id"
  status: "$.message.order.status"
  updated_payments: "$.message.order.payments[*]"
  created_at: "$.message.order.created_at"
  fulfillments: "$.message.order.fulfillments[*]"
  on_confirm_fulfillment: "$.message.order.fulfillments"
  cancellation_terms: "$.message.order.cancellation_terms"
  on_confirm_order: "$.message.order"
