save-data:
  fulfillments: "$.message.order.fulfillments[*]"
  on_update_quote: "$.message.order.quote"
  items: "$.message.order.items[*]"
  quote: "$.message.order.quote"
  quote_trail: $.message.order.fulfillments[*].tags[?(@.code=="quote_trail")]