save-data:
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  fulfillment_end_location: "$.message.order.fulfillments[*].end.location"
  message_id: "$.context.message_id"
