message:
  catalog:
    bpp/providers:
      - id: P1
        locations:
          - id: L1
            time:
              label: close
              timestamp: "2025-01-08T10:20:00.000Z"
              range:
                start: "2025-01-08T16:00:00.000Z"
                end: "2025-01-08T23:59:00.000Z"
