message:
  order:
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: I1
        fulfillment_id: "1"
        category_id: Immediate Delivery
        descriptor:
          code: P2P
    fulfillments:
      - id: "1"
        type: Delivery
        start:
          location:
            id: S1
            gps: "12.453544,77.928379"
            address:
              name: My store name
              building: My building name
              locality: My street name
              city: Bengaluru
              state: Karnataka
              country: India
              area_code: "560041"
          contact:
            phone: "9886098860"
            email: abcd.efgh@gmail.com
        end:
          location:
            gps: "12.4535,77.9283"
            address:
              name: "My house #"
              building: My house or building name
              locality: My street name
              city: Bengaluru
              state: Karnataka
              country: India
              area_code: "560076"
          contact:
            phone: "9886098860"
            email: abcd.efgh@gmail.com
        tags:
          - code: linked_provider
            list:
              - code: id
                value: P1
              - code: name
                value: Seller1
    billing:
      name: ONDC Logistics Buyer NP
      address:
        name: My house or building no
        building: My house or building name
        locality: Jayanagar
        city: Bengaluru
        state: Karnataka
        country: India
        area_code: "560076"
      tax_number: XXXXXXXXXXXXXXX
      phone: "9886098860"
      email: abcd.efgh@gmail.com
      created_at: "2024-11-20T21:30:00.000Z"
      updated_at: "2024-11-20T21:30:00.000Z"
    payment:
      "@ondc/org/collection_amount": "300.00"
      collected_by: BAP
      type: POST-FULFILLMENT
      "@ondc/org/settlement_basis": invoicing
      "@ondc/org/settlement_window": P15D
      "@ondc/org/settlement_details":
        - settlement_counterparty: lbnp
          settlement_type: upi
          beneficiary_name: xxxxx
          upi_address: gft@oksbi
          settlement_bank_account_no: XXXXXXXXXX
          settlement_ifsc_code: XXXXXXXXX
    tags:
      - code: bap_terms
        list:
          - code: accept_bpp_terms
            value: "yes"
