save-data:
  order_id: "$.message.order.id"
  status: "$.message.order.status"
  selected_fulfillments: "$.message.order.fulfillments[*]"
  created_at: "$.message.order.created_at"
  payment_id: "$.message.order.fulfillments[0].id"
  