save-data:
  items: "$.message.order.items[*]"
  fulfillments: "$.message.order.fulfillments[*]"
  fulfillment_end_location: "$.message.order.fulfillments[*].end.location"
  fulfillment_end_contact: "$.message.order.fulfillments[*].end.contact"
  billing: "$.message.order.billing"
  billing_address: "$.message.order.billing.address"
