message:
  order:
    id: O2
    state: In-progress
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: I1
        fulfillment_id: "1"
        category_id: Same Day Delivery
        descriptor:
          code: P2P
        time:
          label: TAT
          duration: PT45M
          timestamp: "2024-11-20"
    quote:
      price:
        currency: INR
        value: "59.00"
      breakup:
        - "@ondc/org/item_id": I1
          "@ondc/org/title_type": delivery
          price:
            currency: INR
            value: "50.0"
        - "@ondc/org/item_id": I1
          "@ondc/org/title_type": tax
          price:
            currency: INR
            value: "9.0"
    fulfillments:
      - id: "1"
        type: Delivery
        state:
          descriptor:
            code: Order-picked-up
        "@ondc/org/awb_no": "1227262193237777"
        tracking: false
        start:
          person:
            name: Ramu
          location:
            id: S1
            gps: "12.4535,77.9283"
            address:
              name: name
              building: My house or building name
              locality: My street name
              city: Bengaluru
              state: Karnataka
              country: India
              area_code: "560041"
          contact:
            phone: "9886098860"
            email: abcd.efgh@gmail.com
          time:
            duration: PT15M
            range:
              start: "2024-11-20T23:45:00.000Z"
              end: "2024-11-20T00:00:00.000Z"
            timestamp: "2024-11-20T00:00:00.000Z"
          instructions:
            code: "2"
            short_desc: value of PCC
            long_desc: additional instructions for pickup
            images:
              - link to downloadable shipping label (required for P2H2P)
            additional_desc:
              content_type: text/html
              url: ..
        end:
          person:
            name: person_name
          location:
            gps: "12.453544,77.928379"
            address:
              name: "My house or building #"
              building: My house or building name
              locality: My street name
              city: Bengaluru
              state: Karnataka
              country: India
              area_code: "560076"
          contact:
            phone: "9886098860"
            email: abcd.efgh@gmail.com
          instructions:
            code: "3"
            short_desc: value of DCC
            long_desc: additional instructions for delivery
            additional_desc:
              content_type: text/html
              url: ..
          time:
            range:
              start: "2024-11-20T02:00:00.000Z"
              end: "2024-11-20T02:15:00.000Z"
        agent:
          name: person_name
          phone: "9886098860"
        vehicle:
          registration: 3LVJ945
        "@ondc/org/ewaybillno": EBN1
        "@ondc/org/ebnexpirydate": "2024-11-20T12:00:00.000Z"
        tags:
          - code: linked_provider
            list:
              - code: id
                value: P1
              - code: name
                value: Seller1
              - code: address
                value: "shop_name,building_name,locality,city,state,pincode"
          - code: linked_order
            list:
              - code: id
                value: RO1
              - code: currency
                value: INR
              - code: declared_value
                value: "300.0"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "3.0"
              - code: dim_unit
                value: centimeter
              - code: length
                value: "1.0"
              - code: breadth
                value: "1.0"
              - code: height
                value: "1.0"
              - code: shipment_type
                value: box
          - code: linked_order_item
            list:
              - code: category
                value: Grocery
              - code: name
                value: Atta
              - code: currency
                value: INR
              - code: value
                value: "70.0"
              - code: quantity
                value: "2"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "1.0"
          - code: linked_order_item
            list:
              - code: category
                value: Grocery
              - code: name
                value: Basmati Rice
              - code: currency
                value: INR
              - code: value
                value: "160.0"
              - code: quantity
                value: "1"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "1.0"
          - code: shipping_label
            list:
              - code: type
                value: pdf
              - code: url
                value: public link to pdf
    billing:
      name: ONDC sellerNP
      address:
        name: My building no
        building: My building name
        locality: My street name
        city: Bengaluru
        state: Karnataka
        country: India
        area_code: "560076"
      tax_number: XXXXXXXXXXXXXXX
      phone: "9886098860"
      email: abcd.efgh@gmail.com
      created_at: "2024-11-20T21:30:00.000Z"
      updated_at: "2024-11-20T21:30:00.000Z"
    payment:
      "@ondc/org/collection_amount": "300.00"
      collected_by: BPP
      type: POST-FULFILLMENT
      "@ondc/org/settlement_basis": invoicing
      "@ondc/org/settlement_window": P15D
      "@ondc/org/settlement_details":
        - settlement_counterparty: lbnp
          settlement_type: upi
          upi_address: gft@oksbi
          settlement_bank_account_no: XXXXXXXXXX
          settlement_ifsc_code: XXXXXXXXX
    "@ondc/org/linked_order":
      items:
        - category_id: Grocery
          descriptor:
            name: Atta
          quantity:
            count: 2
            measure:
              unit: kilogram
              value: 0.5
          price:
            currency: INR
            value: "150.00"
      provider:
        descriptor:
          name: Aadishwar Store
        address:
          name: KHB Towers
          building: Building or House No
          street: 6th Block
          locality: Koramangala
          city: Bengaluru
          state: Karnataka
          area_code: "560070"
      order:
        id: O1
        weight:
          unit: kilogram
          value: 1
        dimensions:
          length:
            unit: centimeter
            value: 1
          breadth:
            unit: centimeter
            value: 1
          height:
            unit: centimeter
            value: 1
    updated_at: "2024-11-20T23:00:30.000Z"
