save-data:
  fulfillments: "$.message.order.fulfillments[*]"
  order_updated_at_timestamp: "$.message.order.updated_at"
  linked_order: $.message.order["@ondc/org/linked_order"]
  quote: "$.message.order.quote"
