catalog:
  bpp/descriptor:
    name: Mock Seller NP
    symbol: https://sellerNP.com/images/np.png
    short_desc: Seller Marketplace
    long_desc: Seller Marketplace
    images:
      - https://sellerNP.com/images/np.png
    tags:
      - code: bpp_terms
        list:
          - code: np_type
            value: MSN

  bpp/providers:
    - id: P1
      items:
        - id: I1
          time:
            label: enable
            timestamp: "2025-07-31T07:16:58.459Z"
          rating: "4"
          descriptor:
            name: Calcium and Vitamin D3 tablets
            symbol: https://snp.com/images/i1.png
            short_desc: Calcium and Vitamin D3 tablets
            long_desc: Calcium and Vitamin D3 tablets
            images:
              - https://snp.com/images/i1.png
            code: "1:XXXXXXXXXXXXX"
          quantity:
            unitized:
              measure:
                unit: unit
                value: "1"
            available:
              count: "99"
            maximum:
              count: "99"
          price:
            currency: INR
            value: "65.00"
            maximum_value: "65.0"
          category_id: Nutrition and Fitness Supplements
          location_id: L1
          fulfillment_id: F1
          "@ondc/org/returnable": true
          "@ondc/org/cancellable": true
          "@ondc/org/available_on_cod": false
          "@ondc/org/time_to_ship": PT45M
          "@ondc/org/seller_pickup_return": true
          "@ondc/org/return_window": PT1H
          "@ondc/org/contact_details_consumer_care": "Ramesh,ramesh@abc.com,18004254444"
          "@ondc/org/statutory_reqs_packaged_commodities":
            manufacturer_or_packer_name: Pure and Cure Healthcare Pvt Ltd
            manufacturer_or_packer_address: Plot No 26A-30, Sector 8A, IIE, SIDCUL, Ranipur, Haridwar-249403
            mfg_license_no: 51/UA/SC/P-2013
            common_or_generic_name_of_commodity: Shelcal HD
            multiple_products_name_number_or_qty: "15"
            month_year_of_manufacture_packing_import: Mar-24
            expiry_date: Feb-25
          "@ondc/org/statutory_reqs_prepackaged_food":
            ingredients_info: >-
              Every film-coated tablet contains: 1250 mg Calcium Carbonate from an organic source (powdered oyster shell)
              equivalent to Elemental Calcium 500 mg, Vitamin D3 I.P 500 IU, Colors: lake of sunset yellow FCF and titanium dioxide I.P
          tags:
            - code: origin
              list:
                - code: country
                  value: IND
            - code: image
              list:
                - code: type
                  value: back_image
                - code: url
                  value: https://snp.com/ondc/images/I1-back.jpg
            - code: attribute
              list:
                - code: brand
                  value: Shellcal HD
                - code: prescription_required
                  value: no
