message:
  order:
    id: O2
    state: In-progress
    cancellation:
      cancelled_by: lsp.com
      reason:
        id: "127"
    provider:
      id: P1

    items:
      - id: I1
        fulfillment_id: "1"
        category_id: Same Day Delivery
        time:
          label: TAT
          duration: PT45M
          timestamp: "2024-11-20"
      - id: I2
        fulfillment_id: 1-RTO
        category_id: Same Day Delivery
        time:
          label: TAT
          duration: PT45M
          timestamp: "2024-11-20"
    quote:
      price:
        currency: INR
        value: "82.60"
      breakup:
        - "@ondc/org/item_id": I1
          "@ondc/org/title_type": delivery
          price:
            currency: INR
            value: "50.00"
        - "@ondc/org/item_id": I1
          "@ondc/org/title_type": tax
          price:
            currency: INR
            value: "9.00"
    fulfillments:
      - id: "1"
        type: Delivery
        state:
          descriptor:
            code: RTO
        "@ondc/org/awb_no": "1227262193237777"
        tracking: true
        start:
          person:
            name: person_name
          location:
            id: S1
            gps: "12.4535,77.9283"
            address:
              name: name
              building: My house or building name
              locality: My street name
              city: Bengaluru
              state: Karnataka
              country: India
              area_code: "560041"
          contact:
            phone: "9886098860"
            email: abcd.efgh@gmail.com
          instructions:
            code: "2"
            short_desc: value of PCC
            long_desc: QR code will be attached to package
            additional_desc:
              content_type: text/html
              url: ..
          time:
            duration: PT15M
            range:
              start: "2024-11-20T22:30:00.000Z"
              end: "2024-11-20T22:45:00.000Z"
        end:
          person:
            name: person_name
          location:
            gps: "12.4535445,77.9283792"
            address:
              name: "My house or building #"
              building: My house or building name
              locality: My street name
              city: Bengaluru
              state: Karnataka
              country: India
              area_code: "560076"
          contact:
            phone: "9886098860"
            email: abcd.efgh@gmail.com
          instructions:
            code: "3"
            short_desc: value of DCC
          time:
            range:
              start: "2024-11-20T23:00:00.000Z"
              end: "2024-11-20T23:15:00.000Z"
        agent:
          name: agent_name
          phone: "9886098860"
        vehicle:
          registration: 3LVJ945
        "@ondc/org/ewaybillno": EBN1
        "@ondc/org/ebnexpirydate": "2023-06-30T12:00:00.000Z"
        tags:
          - code: rto_event
            list:
              - code: retry_count
                value: "3"
              - code: rto_id
                value: F1-RTO
              - code: cancellation_reason_id
                value: "127"
              - code: cancelled_by
                value: lsp.com
          - code: igm_request
            list:
              - code: id
                value: Issue1
          - code: precancel_state
            list:
              - code: fulfillment_state
                value: Order-picked-up
              - code: updated_at
                value: "2023-06-06T23:15:00.000Z"
          - code: linked_provider
            list:
              - code: id
                value: P1
              - code: name
                value: Seller1
              - code: address
                value: "shop_name,building_name,locality,city,state,pincode"
          - code: linked_order
            list:
              - code: id
                value: RO1
              - code: currency
                value: INR
              - code: declared_value
                value: "300.0"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "3.0"
              - code: dim_unit
                value: centimeter
              - code: length
                value: "1.0"
              - code: breadth
                value: "1.0"
              - code: height
                value: "1.0"
              - code: shipment_type
                value: box
          - code: linked_order_item
            list:
              - code: category
                value: Grocery
              - code: name
                value: Atta
              - code: currency
                value: INR
              - code: value
                value: "70.0"
              - code: quantity
                value: "2"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "1.0"
          - code: linked_order_item
            list:
              - code: category
                value: Grocery
              - code: name
                value: Basmati Rice
              - code: currency
                value: INR
              - code: value
                value: "160.0"
              - code: quantity
                value: "1"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "1.0"
          - code: shipping_label
            list:
              - code: type
                value: pdf
              - code: url
                value: public link to pdf
          - code: ebn
            list:
              - code: id
                value: EBN1
              - code: expiry_date
                value: "2024-06-30T12:00:00.000Z"
      - id: 1-RTO
        type: RTO
        state:
          descriptor:
            code: RTO-Initiated
            short_desc: RTO disposed reason code
        start:
          time:
            timestamp: "2024-11-21T14:00:00.000Z"
        tags:
          - code: ebn
            list:
              - code: id
                value: EBN2
              - code: expiry_date
                value: "2024-06-30T12:00:00.000Z"
    billing:
      name: ONDC sellerNP
      address:
        name: My building no
        building: My building name
        locality: My street name
        city: Bengaluru
        state: Karnataka
        country: India
        area_code: "560076"
      tax_number: XXXXXXXXXXXXXXX
      phone: "9886098860"
      email: abcd.efgh@gmail.com
      created_at: "2024-11-20T21:30:00.000Z"
      updated_at: "2024-11-20T21:30:00.000Z"
    payment:
      "@ondc/org/collection_amount": "300.00"
      collected_by: BPP
      status: NOT-PAID
      type: POST-FULFILLMENT
      "@ondc/org/settlement_basis": invoicing
      "@ondc/org/settlement_window": P15D
      "@ondc/org/settlement_details":
        - settlement_counterparty: lbnp
          settlement_type: upi
          upi_address: gft@oksbi
          settlement_bank_account_no: XXXXXXXXXX
          settlement_ifsc_code: XXXXXXXXX
    "@ondc/org/linked_order":
      items:
        - category_id: Grocery
          descriptor:
            name: Atta
          quantity:
            count: 2
            measure:
              unit: kilogram
              value: 0.5
          price:
            currency: INR
            value: "150.00"
      provider:
        descriptor:
          name: Aadishwar Store
        address:
          name: KHB Towers
          building: Building or House No
          locality: Koramangala
          city: Bengaluru
          state: Karnataka
          area_code: "560070"
      order:
        id: O1
        weight:
          unit: kilogram
          value: 1
        dimensions:
          length:
            unit: centimeter
            value: 1
          breadth:
            unit: centimeter
            value: 1
          height:
            unit: centimeter
            value: 1
    created_at: "2024-11-20T22:00:00.000Z"
    updated_at: "2024-11-20T22:00:30.000Z"
