message:
  issue:
    id: ISSUE-1
    status: OPEN
    level: ISSUE
    created_at: '2023-01-15T10:00:00.469Z'
    updated_at: '2023-01-15T10:00:00.469Z'
    expected_response_time:
      duration: PT2H
    expected_resolution_time:
      duration: P1D
    refs:
    - ref_id: O1
      ref_type: ORDER
    - ref_id: P1
      ref_type: PROVIDER
    - ref_id: F1
      ref_type: FULFILLMENT
    actors:
    - id: CUST1
      type: CONSUMER
      info:
        org:
          name: buyerapp.com::ONDC:RET10
        person:
          name: Sam Manuel
        contact:
          phone: '9879879870'
          email: sam@yahoo.com
    - id: NP1
      type: INTERFACING_NP
      info:
        org:
          name: buyerapp.com::ONDC:RET10
        contact:
          phone: '9450394039'
          email: buyerapp@interface.com
        person:
          name: John Doe
    source_id: CUST1
    complainant_id: NP1
    description:
      code: FLM005
      short_desc: Issue with packaging
      long_desc: Food has spilled in the package
      images:
      - url: http://buyerapp.com/addtional-details/img1.png
        size_type: xs
      - url: http://buyerapp.com/addtional-details/img2.png
        size_type: xs
    last_action_id: AR1
    actions:
    - id: AR1
      description:
        code: OPEN
        short_desc: Complaint created
      updated_at: '2023-01-15T10:00:00.469Z'
      action_by: NP1
