session_data:
  transaction_id: null
  message_id: null
  last_action: null
  city_code: null
  bap_id: null
  bap_uri: null
  bpp_id: null
  bpp_uri: null
  status : null
  created_at: null
  updated_at: null
  
 
