message:
  order:
    provider:
      id: "P1"
      locations:
        - id: "L1"
    items:
      - id: "I1"
        parent_item_id: "DI1"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "item"

      - id: "C1"
        parent_item_id: "DI1"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG1"

      - id: "C7"
        parent_item_id: "DI1"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG2"

      - id: "C14"
        parent_item_id: "DI1"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"

      - id: "C16"
        parent_item_id: "DI1"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"

      - id: "I1"
        parent_item_id: "DI2"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "item"

      - id: "C2"
        parent_item_id: "DI2"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG1"

      - id: "C7"
        parent_item_id: "DI2"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG2"

      - id: "C14"
        parent_item_id: "DI2"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"

      - id: "C15"
        parent_item_id: "DI2"
        location_id: "L1"
        quantity:
          count: 1
        tags:
          - code: "type"
            list:
              - code: "type"
                value: "customization"
          - code: "parent"
            list:
              - code: "id"
                value: "CG3"

    fulfillments:
      - end:
          location:
            gps: "12.4535,77.9283"
            address:
              area_code: "560001"
