message:
  update_target: fulfillment
  order:
    id: O2
    items:
      - id: I1
        category_id: Same Day Delivery
    fulfillments:
      - id: "1"
        type: Delivery
        "@ondc/org/awb_no": "1227262193237777"
        start:
          instructions:
            code: "2"
            short_desc: value of PCC
            long_desc: additional instructions for pickup
            additional_desc:
              content_type: text/html
              url: ..
          authorization:
            type: OTP
            token: OTP code
            valid_from: "2024-11-20T12:00:00.000Z"
            valid_to: "2024-11-20T14:00:00.000Z"
        end:
          instructions:
            code: "2"
            short_desc: value of DCC
            long_desc: additional instructions for delivery
        tags:
          - code: state
            list:
              - code: ready_to_ship
                value: "yes"
          - code: linked_provider
            list:
              - code: id
                value: P1
              - code: name
                value: Seller1
              - code: address
                value: "shop_name,building_name,locality,city,state,pincode"
          - code: linked_order
            list:
              - code: id
                value: RO1
              - code: currency
                value: INR
              - code: declared_value
                value: "300.0"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "3.0"
              - code: dim_unit
                value: centimeter
              - code: length
                value: "1.0"
              - code: breadth
                value: "1.0"
              - code: height
                value: "1.0"
              - code: shipment_type
                value: box
          - code: linked_order_item
            list:
              - code: category
                value: Grocery
              - code: name
                value: Atta
              - code: currency
                value: INR
              - code: value
                value: "70.0"
              - code: quantity
                value: "2"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "1.0"
          - code: linked_order_item
            list:
              - code: category
                value: Grocery
              - code: name
                value: Basmati Rice
              - code: currency
                value: INR
              - code: value
                value: "160.0"
              - code: quantity
                value: "1"
              - code: weight_unit
                value: kilogram
              - code: weight_value
                value: "1.0"
    "@ondc/org/linked_order":
      items:
        - category_id: Grocery
          descriptor:
            name: Atta
          quantity:
            count: 2
            measure:
              unit: kilogram
              value: 0.5
          price:
            currency: INR
            value: "150.00"
      order:
        id: O1
        weight:
          unit: kilogram
          value: 1
        dimensions:
          length:
            unit: centimeter
            value: 1
          breadth:
            unit: centimeter
            value: 1
          height:
            unit: centimeter
            value: 1
    updated_at: "2024-11-20T23:00:00.000Z"
