message:
  catalog:
    bpp/providers:
      - id: P1
        items:
          - id: I1
            time:
              label: enable
              timestamp: "2025-01-08T07:30:00.000Z"
            parent_item_id: V1
            descriptor:
              name: Plain Atta
              code: "1:XXXXXXXXXXXXX"
              symbol: "https://snp.com/images/i1.png"
              short_desc: Plain Atta
              long_desc: Plain Atta
              images:
                - "https://snp.com/images/i1.png"
            quantity:
              unitized:
                measure:
                  unit: kilogram
                  value: "1"
              available:
                count: "0"
              maximum:
                count: "0"
            price:
              currency: INR
              value: "65.00"
              maximum_value: "65.00"
            category_id: "Atta, Flours and Sooji"
            fulfillment_id: F1
            location_id: L1
            "@ondc/org/returnable": true
            "@ondc/org/cancellable": true
            "@ondc/org/return_window": PT1H
            "@ondc/org/seller_pickup_return": true
            "@ondc/org/time_to_ship": PT45M
            "@ondc/org/available_on_cod": false
            "@ondc/org/contact_details_consumer_care": "Ramesh,ramesh@abc.com,18004254444"
            "@ondc/org/statutory_reqs_packaged_commodities":
              manufacturer_or_packer_name: ITC
              manufacturer_or_packer_address: "ITC Quality Care Cell,P.O Box No.592,Bangalore-560005"
              common_or_generic_name_of_commodity: Ashirwad Atta
              net_quantity_or_measure_of_commodity_in_pkg: 1kg
              month_year_of_manufacture_packing_import: 01/2025
            "@ondc/org/statutory_reqs_prepackaged_food":
              nutritional_info: >-
                Energy(KCal)-(per 100kg) 420,(per serving
                50g)250;Protein(g)-(per 100kg) 12,(per serving 50g) 6
              additives_info: "Preservatives,Artificial Colours"
              brand_owner_FSSAI_license_no: "12345678901234"
              other_FSSAI_license_no: "12345678901234"
              importer_FSSAI_license_no: "12345678901234"
            tags:
              - code: origin
                list:
                  - code: country
                    value: IND
              - code: image
                list:
                  - code: type
                    value: back_image
                  - code: url
                    value: "https://snp.com/images/i1_back_image.png"
              - code: veg_nonveg
                list:
                  - code: veg
                    value: "yes"
