order:
  items:
    - id: I1
      quantity:
        count: 2
      fulfillment_id: F1
      tags:
        - code: np_fees
          list:
            - code: id
              value: "1"
    - id: I2
      quantity:
        count: 2
      fulfillment_id: F1
  provider:
    id: P1
    locations:
      - id: L1
  fulfillments:
    - "@ondc/org/category": Standard Delivery
      "@ondc/org/TAT": P2D
      "@ondc/org/provider_name": LSP or Provider Name
      id: F1
      tracking: true
      state:
        descriptor:
          code: Serviceable
      end:
        contact:
          email: nobody@nomail.com
          phone: "9898989898"
        person:
          name: ONDC Buyer
        location:
          gps: 19.131140,72.834091
          address:
            building: my building name or house
            city: Mumbai
            state: Maharashtra
            country: IND
            area_code: "400053"
            locality: my street name
            name: my house or door or floor
      type: Delivery
  quote:
    price:
      currency: INR
      value: "1000.50"
    breakup:
      - "@ondc/org/item_id": I1
        "@ondc/org/item_quantity":
          count: 2
        title: MUSTARD JK
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "400.00"
        item:
          price:
            currency: INR
            value: "200.00"
      - "@ondc/org/item_id": I2
        "@ondc/org/item_quantity":
          count: 2
        title: MUSTARD JK
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "600.00"
        item:
          price:
            currency: INR
            value: "300.00"
      - "@ondc/org/item_id": F1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "0.00"
      - "@ondc/org/item_id": I1
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "0.50"
        item:
          tags:
            - code: quote
              list:
                - code: type
                  value: item
            - code: np_fees
              list:
                - code: id
                  value: "1"
                - code: channel_margin_type
                  value: percent
                - code: channel_margin_value
                  value: "0.50"
      - "@ondc/org/item_id": I1
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "7.00"
        item:
          tags:
            - code: quote
              list:
                - code: type
                  value: item
            - code: np_fees
              list:
                - code: id
                  value: "2"
                - code: channel_margin_type
                  value: amount
                - code: channel_margin_value
                  value: "7.00"
      - "@ondc/org/item_id": I1
        "@ondc/org/title_type": tax
        price:
          currency: INR
          value: "0.00"
        item:
          tags:
            - code: quote
              list:
                - code: type
                  value: item
                - code: subtype
                  value: misc
            - code: np_fees
              list:
                - code: id
                  value: "1"
      - "@ondc/org/item_id": I1
        "@ondc/org/title_type": tax
        price:
          currency: INR
          value: "0.00"
        item:
          tags:
            - code: quote
              list:
                - code: type
                  value: item
                - code: subtype
                  value: misc
            - code: np_fees
              list:
                - code: id
                  value: "2"
    ttl: PT1H