message:
  order:
    id: "O1"
    state: "Completed"
    provider:
      id: "P1"
      locations:
      - id: "L1"
    items:
    - id: "I1"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI1"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "item"
    - id: "C1"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI1"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG1"
    - id: "C7"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI1"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG2"
    - id: "C14"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI1"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG3"
    - id: "C16"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI1"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG3"
    - id: "I1"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI2"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "item"
    - id: "C2"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI2"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG1"
    - id: "C7"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI2"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG2"
    - id: "C14"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI2"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG3"
    - id: "C15"
      fulfillment_id: "F1"
      quantity:
        count: 1
      parent_item_id: "DI2"
      tags:
      - code: "type"
        list:
        - code: "type"
          value: "customization"
      - code: "parent"
        list:
        - code: "id"
          value: "CG3"
    billing:
      name: "ONDC buyer"
      address:
        name: "my house or door or floor #"
        building: "my building name or house #"
        locality: "my street name"
        city: "Bengaluru"
        state: "Karnataka"
        country: "IND"
        area_code: "560037"
      email: "nobody@nomail.com"
      phone: "9886098860"
      created_at: "2025-01-08T09:00:00.000Z"
      updated_at: "2025-01-08T09:00:00.000Z"
    fulfillments:
    - id: "F1"
      "@ondc/org/provider_name": "LSP or Provider name"
      type: "Delivery"
      tracking: false
      "@ondc/org/TAT": "PT60M"
      state:
        descriptor:
          code: "Order-delivered"
      start:
        location:
          descriptor:
            name: "ABC Store"
          gps: "12.9675,77.7496"
          address:
            locality: "Jayanagar"
            city: "Bengaluru"
            area_code: "560076"
            state: "KA"
        time:
          timestamp: "2025-01-08T10:25:00.000Z"
        contact:
          phone: "9886098860"
          email: "nobody@nomail.com"
      end:
        location:
          gps: "12.4535,77.9283"
          address:
            name: "my house or door or floor #"
            building: "my building name or house #"
            locality: "my street name"
            city: "Bengaluru"
            state: "Karnataka"
            country: "IND"
            area_code: "560037"
        time:
          timestamp: "2025-01-08T11:35:00.000Z"
        person:
          name: "name_of_person"
        contact:
          phone: "9886098860"
      agent:
        name: "agent_name"
        phone: "9886098860"
      tags:
      - code: "routing"
        list:
        - code: "type"
          value: "P2P"
      - code: "tracking"
        list:
        - code: "gps_enabled"
          value: "yes"
        - code: "url_enabled"
          value: "no"
        - code: "url"
          value: "https://snp.com/ondc/tracking_url"
    quote:
      price:
        currency: "INR"
        value: "1955.65"
      breakup:
      - "@ondc/org/item_id": "I1"
        "@ondc/org/item_quantity":
          count: 1
        title: "Farm House Pizza"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "269.00"
        item:
          parent_item_id: "DI1"
          price:
            currency: "INR"
            value: "269.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "item"
      - "@ondc/org/item_id": "C1"
        "@ondc/org/item_quantity":
          count: 1
        title: "New Hand Tossed"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "0.00"
        item:
          parent_item_id: "DI1"
          price:
            currency: "INR"
            value: "0.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG1"
      - "@ondc/org/item_id": "C7"
        "@ondc/org/item_quantity":
          count: 1
        title: "Large"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "450.00"
        item:
          parent_item_id: "DI1"
          price:
            currency: "INR"
            value: "450.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG2"
      - "@ondc/org/item_id": "C14"
        "@ondc/org/item_quantity":
          count: 1
        title: "Grilled Mushrooms"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "80.00"
        item:
          parent_item_id: "DI1"
          price:
            currency: "INR"
            value: "80.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "C16"
        "@ondc/org/item_quantity":
          count: 1
        title: "Pepper Barbeque Chicken"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "95.00"
        item:
          parent_item_id: "DI1"
          price:
            currency: "INR"
            value: "95.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "I1"
        "@ondc/org/item_quantity":
          count: 1
        title: "Farm House Pizza"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "269.00"
        item:
          parent_item_id: "DI2"
          price:
            currency: "INR"
            value: "269.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "item"
      - "@ondc/org/item_id": "C2"
        "@ondc/org/item_quantity":
          count: 1
        title: "100% Wheat Thin Crust"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "0.00"
        item:
          parent_item_id: "DI2"
          price:
            currency: "INR"
            value: "0.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG1"
      - "@ondc/org/item_id": "C7"
        "@ondc/org/item_quantity":
          count: 1
        title: "Large"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "450.00"
        item:
          parent_item_id: "DI2"
          price:
            currency: "INR"
            value: "450.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG2"
      - "@ondc/org/item_id": "C14"
        "@ondc/org/item_quantity":
          count: 1
        title: "Grilled Mushrooms"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "80.00"
        item:
          parent_item_id: "DI2"
          price:
            currency: "INR"
            value: "80.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "C15"
        "@ondc/org/item_quantity":
          count: 1
        title: "Fresh Tomato"
        "@ondc/org/title_type": "item"
        price:
          currency: "INR"
          value: "80.00"
        item:
          parent_item_id: "DI2"
          price:
            currency: "INR"
            value: "80.00"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "I1"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "13.45"
        item:
          parent_item_id: "DI1"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "item"
      - "@ondc/org/item_id": "C1"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "0.00"
        item:
          parent_item_id: "DI1"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG1"
      - "@ondc/org/item_id": "C7"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "22.50"
        item:
          parent_item_id: "DI1"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG2"
      - "@ondc/org/item_id": "C14"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "4.00"
        item:
          parent_item_id: "DI1"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "C16"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "4.75"
        item:
          parent_item_id: "DI1"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG1"
      - "@ondc/org/item_id": "I1"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "13.45"
        item:
          parent_item_id: "DI2"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "item"
      - "@ondc/org/item_id": "C2"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "22.50"
        item:
          parent_item_id: "DI2"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG1"
      - "@ondc/org/item_id": "C7"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "22.50"
        item:
          parent_item_id: "DI2"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG2"
      - "@ondc/org/item_id": "C14"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "4.00"
        item:
          parent_item_id: "DI2"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "C15"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "4.00"
        item:
          parent_item_id: "DI2"
          tags:
          - code: "type"
            list:
            - code: "type"
              value: "customization"
          - code: "parent"
            list:
            - code: "id"
              value: "CG3"
      - "@ondc/org/item_id": "F1"
        title: "Delivery charges"
        "@ondc/org/title_type": "delivery"
        price:
          currency: "INR"
          value: "50.00"
      - "@ondc/org/item_id": "F1"
        title: "Tax"
        "@ondc/org/title_type": "tax"
        price:
          currency: "INR"
          value: "9.00"
        item:
          tags:
          - code: "quote"
            list:
            - code: "type"
              value: "fulfillment"
      - "@ondc/org/item_id": "F1"
        title: "Packing charges"
        "@ondc/org/title_type": "packing"
        price:
          currency: "INR"
          value: "25.00"
      - "@ondc/org/item_id": "F1"
        title: "Convenience Fee"
        "@ondc/org/title_type": "misc"
        price:
          currency: "INR"
          value: "10.00"
      ttl: "PT1H"
    payment:
      uri: "https://ondc.transaction.com/payment"
      tl_method: "http/get"
      params:
        currency: "INR"
        transaction_id: "3937"
        amount: "1955.65"
      status: "PAID"
      type: "ON-ORDER"
      collected_by: "BAP"
      "@ondc/org/buyer_app_finder_fee_type": "percent"
      "@ondc/org/buyer_app_finder_fee_amount": "3.54"
      "@ondc/org/settlement_basis": "delivery"
      "@ondc/org/settlement_window": "P1D"
      "@ondc/org/withholding_amount": "10.00"
      "@ondc/org/settlement_details":
      - settlement_counterparty: "seller-app"
        settlement_phase: "sale-amount"
        beneficiary_name: "xxxxx"
        settlement_reference: "XXXX"
        settlement_status: "PAID"
        settlement_timestamp: "2025-01-08T10:00:00.000Z"
        settlement_type: "upi"
        upi_address: "gft@oksbi"
        settlement_bank_account_no: "XXXXXXXXXX"
        settlement_ifsc_code: "XXXXXXXXX"
        bank_name: "xxxx"
        branch_name: "xxxx"
    documents:
    - url: "https://invoice_url"
      label: "Invoice"
    created_at: "2025-01-08T09:30:00.000Z"
    updated_at: "2025-01-08T10:00:30.201Z"
