save-data:
  order_id: "$.message.order.id"
  order_status: "$.message.order.state"
  message_id: "$.context.message_id"
  confirm_create_at_timestamp: "$.message.order.created_at"
  tat: "$.message.order.items[0].time.duration"
  fulfillments: "$.message.order.fulfillments[*]"
  confirm_fulfillments: "$.message.order.fulfillments[*]"
  items: "$.message.order.items[*]"
