message:
  catalog:
    bpp/descriptor:
      name: LSP Aggregator Inc
      tags:
        - code: bpp_terms
          list:
            - code: static_terms
              value: ""
            - code: static_terms_new
              value: >-
                https://github.com/ONDC-Official/NP-Static-Terms/lspNP_LSP/1.0/tc.pdf
            - code: effective_date
              value: "2024-11-20T00:00:00.000Z"
    bpp/providers:
      - id: P1
        descriptor:
          name: LSP Courier Inc
          short_desc: LSP Courier Inc
          long_desc: LSP Courier Inc
        categories:
          - id: Immediate Delivery
            time:
              label: TAT
              duration: PT60M
              timestamp: "2024-11-20"
        fulfillments:
          - id: "1"
            type: Batch
            start:
              time:
                duration: PT15M
            tags:
              - code: distance
                list:
                  - code: motorable_distance_type
                    value: kilometer
                  - code: motorable_distance
                    value: "1.8"
          - id: "2"
            type: RTO
        items:
          - id: I1
            parent_item_id: ""
            category_id: Immediate Delivery
            fulfillment_id: "1"
            descriptor:
              name: Fast delivery
              short_desc: Fast delivery services
              long_desc: Fast delivery services
            price:
              currency: INR
              value: "59.00"
            time:
              label: TAT
              duration: PT45M
              timestamp: "2024-11-20"
             