message:
  order:
    id: 077b248f
    status: ACTIVE
    items:
      - id: I3
        descriptor:
          name: Journey Pass
          code: PASS
        category_ids:
          - C2
        price:
          currency: INR
          value: '1500'
        quantity:
          selected:
            count: 1
        fulfillment_ids:
          - F2
        time:
          label: Validity
          duration: P30D
    provider:
      id: P1
      descriptor:
        name: ONDC Metro Rail Limited
        images:
          - url: 'https://delhimetrorail.com/logos/logo.ico'
      time:
        range:
          start: '2023-09-14T05:30:00.000Z'
          end: '2023-09-14T23:30:00.000Z'
    fulfillments:
      - id: F2
        type: TRIP
        state:
          descriptor:
            code: PASS_ACTIVE
        stops:
          - type: START
            location:
              descriptor:
                name: Shaheed Sthal(New Bus Adda)
                code: SHAHEED_STHAL
              gps: '28.686576, 77.441632'
            authorization:
              type: QR
              token: 8ed21b6f
              valid_to: '2027-12-31T23:59:59.999Z'
              status: UNCLAIMED
            id: '1'
          - type: END
            location:
              descriptor:
                name: Azadpur
                code: AZADPUR
              gps: '28.707358, 77.180910'
            id: '2'
            parent_stop_id: '1'
        vehicle:
          category: METRO
        tags:
          - descriptor:
              code: PASS_INFO
            display: false
            list:
              - descriptor:
                  code: AVAILABLE_TRIPS
                value: '30'
              - descriptor:
                  code: UTILIZED_TRIPS
                value: '0'
    cancellation_terms:
      - external_ref:
          mimetype: text/html
          url: 'https://transitsolutions.com/mf/tnc.html'
    tags:
      - descriptor:
          code: SCHEDULED_INFO
        display: false
        list:
          - descriptor:
              code: GTFS
            value: 'https://metro-transit/gtfs-realtime'
    billing:
      name: John Doe
      email: john.doe@example.com
      phone: +91-9897867564
    quote:
      price:
        value: '1500'
        currency: INR
      breakup:
        - title: BASE_FARE
          item:
            id: I3
            price:
              currency: INR
              value: '1500'
            quantity:
              selected:
                count: 1
          price:
            currency: INR
            value: '1500'
    payments:
      - id: PA1
        collected_by: BAP
        status: PAID
        type: PRE-ORDER
        params:
          transaction_id: 34cc9b0b-6887-4c63-8397-2f4fcf03e50d
          currency: INR
          amount: '1500'
          bank_code: XXXXXXXX
          bank_account_number: xxxxxxxxxxxxxx
        tags:
          - descriptor:
              code: BUYER_FINDER_FEES
            display: false
            list:
              - descriptor:
                  code: BUYER_FINDER_FEES_PERCENTAGE
                value: '1'
              - descriptor:
                  code: BUYER_FINDER_FEES_TYPE
                value: percent
          - descriptor:
              code: SETTLEMENT_TERMS
            display: false
            list:
              - descriptor:
                  code: SETTLEMENT_WINDOW
                value: P30D
              - descriptor:
                  code: SETTLEMENT_BASIS
                value: INVOICE_RECEIPT
              - descriptor:
                  code: MANDATORY_ARBITRATION
                value: 'true'
              - descriptor:
                  code: COURT_JURISDICTION
                value: New Delhi
              - descriptor:
                  code: STATIC_TERMS
                value: 'https://api.example-bpp.com/booking/terms'
              - descriptor:
                  code: SETTLEMENT_AMOUNT
                value: '1485'
              - descriptor:
                  code: SETTLEMENT_TYPE
                value: NEFT
    created_at: '2021-03-23T10:00:40.065Z'
    updated_at: '2021-03-23T10:00:40.065Z'
