message:
  order:
    billing:
      name: Rahul Kumar # Customer's full name
    fulfillments:
      - customer:
          contact:
            phone: "9898989898" # Customer's contact number
          person:
            name: Rahul Kumar # Customer's name for the ride
        id: TRIP_001 # Unique trip identifier
        stops:
          - location:
              gps: "12.9279232,77.6271078" # Indiranagar, Bangalore
            type: START
          - location:
              gps: "12.9767936,77.5713319" # Malleshwaram, Bangalore
            type: END
        vehicle:
          category: AUTO_RICKSHAW # Vehicle type requested
          variant: AUTO_RICKSHAW # Specific variant of the vehicle
    items:
      - id: ITEM_AUTO_001 # Reference to the selected auto-rickshaw
    tags:
      - descriptor:
          name: BAP Terms of Engagement # Business terms between BAP and BPP
          code: BAP_TERMS
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "3" # Standard marketplace fee percentage
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: PT24H # 24 hour settlement window
          - descriptor:
              code: SETTLEMENT_BASIS
            value: DELIVERY # Settlement after successful delivery/trip completion
          - descriptor:
              code: SETTLEMENT_TYPE
            value: UPI # Payment settlement method
          - descriptor:
              code: MANDATORY_ARBITRATION
            value: "true" # Mandatory arbitration for disputes
          - descriptor:
              code: COURT_JURISDICTION
            value: Bangalore # Legal jurisdiction for disputes
          - descriptor:
              code: DELAY_INTEREST
            value: "12" # Annual interest rate for delayed settlements
          - descriptor:
              code: STATIC_TERMS
            value: https://example-test-bpp.com/mobility/terms-v2.html # Terms and conditions URL
          - descriptor:
              code: SETTLEMENT_BANK_CODE
            value: HDFC0001234 # Bank IFSC code
          - descriptor:
              code: SETTLEMENT_BANK_ACCOUNT_NUMBER
            value: "50100047218903" # Settlement bank account number
          - descriptor:
              code: SETTLEMENT_VIRTUAL_PAYMENT_ADDRESS
            value: mobility.provider@hdfcbank # UPI VPA for settlements
    payments:
      - collected_by: BPP # Payment collected by mobility service provider
        status: NOT-PAID # Current payment status
        type: ON-FULFILLMENT # Payment collected after trip completion
    provider:
      id: PROV_MOBILITY_001 # Mobility service provider ID
