codes:
  - code: 100
    action_id: search_LOGISTICS
    action: search
    default: search/default.yaml
    message_id: true
  - code: 101
    action_id: init_LOGISTICS
    action: search
    default: init/default.yaml
    message_id: true
  - code: 102
    action_id: confirm_LOGISTICS
    action: confirm
    default: confirm/default.yaml
    message_id: true
  - code: 103
    action_id: update_LOGISTICS
    action: update
    default: update/default.yaml
    message_id: true
  - code: 104
    action_id: track_LOGISTICS
    action: track
    default: track/default.yaml
    message_id: true
  - code: 105
    action_id: on_search_LOGISTICS
    action: on_search
    default: on_search/default.yaml
    message_id: false
  - code: 106
    action_id: on_init_LOGISTICS
    action: on_init
    default: on_init/default.yaml
    message_id: false
  - code: 107
    action_id: on_confirm_LOGISTICS
    action: on_confirm
    default: on_confirm/default.yaml
    message_id: false
  - code: 108
    action_id: cancel_LOGISTICS
    action: cancel
    default: cancel/default.yaml
    message_id: true
  - code: 109
    action_id: on_update_LOGISTICS
    action: on_update
    default: on_update/default.yaml
    message_id: false
  - code: 110
    action_id: on_status_LOGISTICS
    action: on_status
    default: on_status/default.yaml
    message_id: false
  - code: 111
    action_id: on_track_LOGISTICS
    action: on_track
    default: on_track/default.yaml
    message_id: false
