message:
  order:
    id: O1
    state: Completed
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: I1
        fulfillment_id: F1
        quantity:
          count: 2
    billing:
      name: ONDC buyer
      address:
        name: my house or door or floor #
        building: my building name or house #
        locality: my street name
        city: Bengaluru
        state: Karnataka
        country: IND
        area_code: '560037'
      email: nobody@nomail.com
      phone: '9886098860'
      created_at: '2025-01-08T09:00:00.000Z'
      updated_at: '2025-01-08T09:00:00.000Z'
    fulfillments:
      - id: F1
        @ondc/org/provider_name: LSP or Provider Name
        type: Delivery
        tracking: true
        @ondc/org/TAT: PT60M
        state:
          descriptor:
            code: Order-delivered
        start:
          location:
            id: L1
            descriptor:
              name: ABC Store
            gps: 12.9563,77.6368
            address:
              locality: Jayanagar
              city: Bengaluru
              area_code: '560076'
              state: KA
          time:
            timestamp: '2025-01-08T10:25:00.000Z'
          contact:
            phone: '9886098860'
            email: nobody@nomail.com
        end:
          location:
            gps: 12.4535,77.9283
            address:
              name: my house or door or floor #
              building: my building name or house #
              locality: my street name
              city: Bengaluru
              state: Karnataka
              country: IND
              area_code: '560037'
          time:
            timestamp: '2025-01-08T11:35:00.000Z'
          person:
            name: name_of_person
          contact:
            phone: '9886098860'
            email: nobody@nomail.com
        agent:
          name: agent_name
          phone: '9886098860'
      - id: R1
        type: Return
        state:
          descriptor:
            code: Return_Initiated
        tags:
          - code: return_request
            list:
              - code: id
                value: R1
              - code: item_id
                value: I1
              - code: item_quantity
                value: '1'
              - code: reason_id
                value: '003'
              - code: reason_desc
                value: detailed description for return
              - code: images
                value: url_for_image1,url_for_image2
              - code: ttl_approval
                value: PT24H
              - code: ttl_reverseqc
                value: P3D
              - code: initiated_by
                value: bnp.com
