save-data:
  order_id: "$.message.order.id"
  order_status: "$.message.order.state"
  fulfillment_pickup_timestamp: "$.message.order.fulfillments[?(@.type=='Delivery')].start.time.timestamp"
  fulfillments: "$.message.order.fulfillments[*]"
  order_updated_at_timestamp: "$.message.order.updated_at"
  payment: "$.message.order.payment"
  linked_order: $.message.order["@ondc/org/linked_order"]
