message:
  tracking:
    id: F1
    url: "https://lsp.com/ondc/track/"
    location:
      gps: "12.9740,77.6134"
      time:
        timestamp: "2024-11-20T23:30:00.000Z"
      updated_at: "2024-11-20T23:31:00.000Z"
    status: active
    tags:
      - code: order
        list:
          - code: id
            value: O2
      - code: config
        list:
          - code: attr
            value: tracking.location.gps
          - code: type
            value: live_poll
      - code: path
        list:
          - code: lat_lng
            value: "12.9740,77.6134"
          - code: sequence
            value: "1"
      - code: path
        list:
          - code: lat_lng
            value: "12.9740,77.6136"
          - code: sequence
            value: "2"
      - code: path
        list:
          - code: lat_lng
            value: "12.9740,77.6137"
          - code: sequence
            value: "3"
