order:
  provider:
    id: P1
    locations:
      - id: L1
  fulfillments:
    - id: F32822
      type: Buyer-Delivery
      "@ondc/org/provider_name": ""
      tracking: false
      "@ondc/org/category": ""
      "@ondc/org/TAT": P2D
      state:
        descriptor:
          code: Serviceable
      tags:
        - code: weight
          list:
            - code: unit
              value: kilogram
            - code: value
              value: "1"
        - code: length
          list:
            - code: unit
              value: centimeter
            - code: value
              value: "1"
        - code: breadth
          list:
            - code: unit
              value: centimeter
            - code: value
              value: "1"
        - code: height
          list:
            - code: unit
              value: centimeter
            - code: value
              value: "1"
  quote:
    price:
      value: "100.00"
      currency: INR
    breakup:
      - "@ondc/org/item_id": I1
        "@ondc/org/item_quantity":
          count: 1
        title: Plain Atta
        "@ondc/org/title_type": item
        price:
          currency: INR
          value: "100.00"
        item:
          quantity:
            available:
              count: "99"
            maximum:
              count: "99"
          price:
            currency: INR
            value: "100.00"
      - "@ondc/org/item_id": F1
        title: Delivery charges
        "@ondc/org/title_type": delivery
        price:
          currency: INR
          value: "00.00"
      - "@ondc/org/item_id": F1
        title: Convenience Fee
        "@ondc/org/title_type": misc
        price:
          currency: INR
          value: "00.00"
    ttl: P1D
  items:
    - id: I1
      fulfillment_id: F2
