save-data:
  fulfillments: $.message.order.fulfillments[*]
  tags: $.message.order.tags[*]
  bpp_terms: $.message.order.tags[?(@.code == 'bpp_terms')]
  quote: $.message.order.quote
  payment: $.message.order.payment
  on_init_payment: $.message.order.payment["@ondc/org/settlement_details"]
