update_target: fulfillment
order:
  id: 2024-08-08-739546
  fulfillments:
    - id: F3
      tags:
        - code: update_state
          list:
            - code: state
              value: Order-delivered
        - code: update_fulfillment_time
          list:
            - code: state
              value: Order-delivered
            - code: timestamp
              value: "2024-08-12T10:10:58.799Z"
            - code: start_time
              value: "2024-08-12T10:09:58.799Z"
            - code: end_time
              value: "2024-08-12T11:11:58.799Z"
