session_data:
  transaction_id: null
  message_id: null
  city: null
  inc_mode: null
  selected_items: []
  selected_fulfillments: []
  items: []
  provider: null
  billing: null
  fulfillments: []
  quote: null
  order_id: null
  payment: null
  order_state: null
  order_created_at: null
  on_select_fulfillments: []
  on_status_fulfillments: []
  tags: []
  bap_terms: null
  bpp_terms: null
  out_of_stock_item_ids: []
  cancellation_reason_id: null
  update_fulfillments: []
