message:
  catalog:
    bpp/providers:
      - id: P1
        items:
          - id: I1
            time:
              label: enable
              timestamp: "2025-01-08T07:30:00.000Z"
            rating: "4"
            descriptor:
              name: Farm House Pizza
              symbol: "https://snp.com/images/i1.png"
              short_desc: Farm House Pizza
              long_desc: Farm House Pizza
              images:
                - "https://snp.com/images/i1.png"
            quantity:
              unitized:
                measure:
                  unit: unit
                  value: "1"
              available:
                count: "99"
              maximum:
                count: "99"
            price:
              currency: INR
              value: "259.00"
              maximum_value: "259.00"
              tags:
                - code: range
                  list:
                    - code: lower
                      value: "259.00"
                    - code: upper
                      value: "894.00"
            category_id: F&B
            category_ids:
              - "5:1"
            fulfillment_id: F1
            location_id: L1
            related: false
            recommended: true
            "@ondc/org/returnable": false
            "@ondc/org/cancellable": false
            "@ondc/org/return_window": PT1H
            "@ondc/org/seller_pickup_return": false
            "@ondc/org/time_to_ship": PT45M
            "@ondc/org/available_on_cod": false
            "@ondc/org/contact_details_consumer_care": "Ramesh,ramesh@abc.com,18004254444"
            tags:
              - code: type
                list:
                  - code: type
                    value: item
              - code: custom_group
                list:
                  - code: id
                    value: CG1
              - code: timing
                list:
                  - code: day_from
                    value: "1"
                  - code: day_to
                    value: "5"
                  - code: time_from
                    value: "1800"
                  - code: time_to
                    value: "2200"
              - code: veg_nonveg
                list:
                  - code: veg
                    value: "yes"
