message:
  update_target:
    - path: issue.actions
      action: APPENDED
  issue:
    id: ISSUE-1
    status: PROCESSING
    level: ISSUE
    created_at: '2023-01-15T10:00:00.469Z'
    updated_at: '2023-01-15T10:00:00.469Z'
    expected_response_time:
      duration: PT2H
    expected_resolution_time:
      duration: P1D
    refs:
      - ref_id: O1
        ref_type: ORDER
      - ref_id: P1
        ref_type: PROVIDER
      - ref_id: F1
        ref_type: FULFILLMENT
      - ref_id: I1
        ref_type: ITEM
        tags:
          - descriptor:
              code: message.order.items
            list:
              - descriptor:
                  code: quantity.selected.count
                value: '2'
    actors:
      - id: CUST1
        type: CONSUMER
        info:
          org:
            name: 'buyerapp.com::ONDC:RET10'
          person:
            name: Sam Manuel
          contact:
            phone: '9879879870'
            email: sam@yahoo.com
      - id: NP1
        type: INTERFACING_NP
        info:
          org:
            name: 'buyerapp.com::ONDC:RET10'
          contact:
            phone: '9450394039'
            email: buyerapp@interface.com
          person:
            name: John Doe
      - id: NP2
        type: COUNTERPARTY_NP
        info:
          org:
            name: 'sellerapp.com::ONDC:RET10'
          contact:
            phone: '9450394140'
            email: respondentapp@respond.com
          person:
            name: Jane Doe
    source_id: CUST1
    complainant_id: NP1
    respondent_ids:
      - NP2
    descriptor:
      code: ITM004
      short_desc: Issue with product quality
      long_desc: product quality is not correct. facing issues while using the product
      additional_desc:
        url: 'https://buyerapp.com/additonal-details/desc.txt'
        content_type: text/plain
      images:
        - url: 'http://buyerapp.com/addtional-details/img1.png'
          size_type: xs
        - url: 'http://buyerapp.com/addtional-details/img2.png'
          size_type: xs
    last_action_id: A2
    actions:
      - id: A1
        descriptor:
          code: OPEN
          short_desc: Complaint created
        updated_at: '2023-01-15T10:00:00.469Z'
        action_by: NP1
        actor_details:
          name: Sam Manuel
      - id: A2
        descriptor:
          code: PROCESSING
          short_desc: Complaint created
        updated_at: '2023-01-15T10:00:10.469Z'
        action_by: NP2
        actor_details:
          name: Sam Manuel
