message:
  order:
    id: O1
    state: Accepted
    provider:
      id: P1
      locations:
        - id: L1
    items:
      - id: I1
        fulfillment_id: F1
        quantity:
          count: 1
      - id: I1
        fulfillment_id: C1
        quantity:
          count: 1
    billing:
      name: ONDC buyer
      address:
        name: my house or door or floor #
        building: my building name or house #
        locality: my street name
        city: Bengaluru
        state: Karnataka
        country: IND
        area_code: "560037"
      email: nobody@nomail.com
      phone: "9886098860"
      created_at: "2025-01-08T09:00:00.000Z"
      updated_at: "2025-01-08T09:00:00.000Z"
    fulfillments:
      - id: F1
        @ondc/org/provider_name: LSP or Provider Name
        type: Delivery
        tracking: true
        @ondc/org/TAT: PT60M
        state:
          descriptor:
            code: Pending
        start:
          location:
            id: L1
            descriptor:
              name: ABC Store
            gps: "12.9563,77.6368"
            address:
              locality: Jayanagar
              city: Bengaluru
              area_code: "560076"
              state: KA
          contact:
            phone: "9886098860"
            email: nobody@nomail.com
        end:
          location:
            gps: "12.4535,77.9283"
            address:
              name: my house or door or floor #
              building: my building name or house #
              locality: my street name
              city: Bengaluru
              state: Karnataka
              country: IND
              area_code: "560037"
          person:
            name: name_of_person
          contact:
            phone: "9886098860"
            email: nobody@nomail.com
      - id: C1
        type: Cancel
        state:
          descriptor:
            code: Cancelled
        tags:
          - code: cancel_request
            list:
              - code: reason_id
                value: "002"
              - code: initiated_by
                value: snp.com
          - code: quote_trail
            list:
              - code: type
                value: item
              - code: id
                value: I1
              - code: currency
                value: INR
              - code: value
                value: "-170.00"
          - code: quote_trail
            list:
              - code: type
                value: tax
              - code: id
                value: I1
              - code: currency
                value: INR
              - code: value
                value: "0.00"
    quote:
      price:
        currency: INR
        value: "254.00"
      breakup:
        - @ondc/org/item_id: I1
          @ondc/org/item_quantity:
            count: 1
          title: Atta
          @ondc/org/title_type: item
          price:
            currency: INR
            value: "170.00"
          item:
            price:
              currency: INR
              value: "170.00"
        - @ondc/org/item_id: F1
          title: Delivery charges
          @ondc/org/title_type: delivery
          price:
            currency: INR
            value: "50.00"
        - @ondc/org/item_id: F1
          title: Tax
          @ondc/org/title_type: tax
          price:
            currency: INR
            value: "9.00"
          item:
            tags:
              - code: quote
                list:
                  - code: type
                    value: fulfillment
        - @ondc/org/item_id: F1
          title: Packing charges
          @ondc/org/title_type: packing
          price:
            currency: INR
            value: "25.00"
        - @ondc/org/item_id: I1
          title: Tax
          @ondc/org/title_type: tax
          price:
            currency: INR
            value: "0.00"
        - @ondc/org/item_id: I1
          title: Discount
          @ondc/org/title_type: discount
          price:
            currency: INR
            value: "-10.00"
        - @ondc/org/item_id: F1
          title: Convenience Fee
          @ondc/org/title_type: misc
          price:
            currency: INR
            value: "10.00"
      ttl: P1D
    payment:
      uri: https://ondc.transaction.com/payment
      params:
        currency: INR
        transaction_id: "3937"
        amount: "424.00"
      status: PAID
      type: ON-ORDER
      collected_by: BAP
      @ondc/org/buyer_app_finder_fee_type: percent
      @ondc/org/buyer_app_finder_fee_amount: "3.54"
      @ondc/org/settlement_details:
        - settlement_counterparty: seller-app
          settlement_phase: sale-amount
          beneficiary_name: xxxxx
          settlement_type: upi
          upi_address: gft@oksbi
          settlement_bank_account_no: XXXXXXXXXX
          settlement_ifsc_code: XXXXXXXXX
          bank_name: xxxx
          branch_name: xxxx
    created_at: "2025-01-08T09:30:00.000Z"
    updated_at: "2025-01-08T10:31:30.000Z"
